name = "cookie-cloudflare"
main = "src/app.ts"
minify = false
compatibility_date = "2024-10-20"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "R2"
bucket_name = "cookie-cloudflare"

[env.dev]
# Development environment configuration
main = "src/app.ts"
minify = false

[[env.dev.r2_buckets]]
binding = "R2"
bucket_name = "cookie-cloudflare"

[env.production]
# Production environment configuration
main = "dist/app.mjs"
minify = true
