name = "cookie-cloudflare"
main = "src/app.ts"
minify = false
compatibility_date = "2024-10-20"
compatibility_flags = ["nodejs_compat"]

[env.dev]
# Development environment configuration
main = "src/app.ts"
minify = false

[env.production]
# Production environment configuration
main = "dist/app.mjs"
minify = true

[[d1_databases]]
# available in your Worker on env.DB
binding = "DB"
database_name = "${D1_DATABASE_NAME}"
database_id = "${D1_DATABASE_ID}"
