name = "cookie-cloudflare"
main = "dist/app.mjs"
minify = true
compatibility_date = "2024-10-20"
compatibility_flags = ["nodejs_compat"]
[vars]
CACHE_MAX_AGE = '3600'

[[r2_buckets]]
binding = "R2"
bucket_name = "cookie-cloudflare"

[env.dev]
# Development environment configuration
main = "src/app.ts"
minify = false

[[env.dev.r2_buckets]]
binding = "R2"
bucket_name = "cookie-cloudflare"

[env.dev.vars]
CACHE_MAX_AGE = '600'

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
